namespace splatform.tiles;
// TODO: Probably ignore this.
internal class PipeOrigin : Tile {
    /// <summary>
    /// The amount of entities that have been generated by this tile already.
    /// </summary>
    private int _generationCount = 0;

    public bool ContainsEntity { get; init; } = false;
    // entity

    public bool GeneratesEntity { get; init; } = false;
    // entity
    public int MaxGenerationCount { get; init; } = 0;

    public bool ContainsWarp { get; init; } = false;
}
