using splatform.entities;

namespace splatform.tiles;
// TODO: Probably ignore this.
internal class PipeOrigin : OldTile {
    #region Parameters
    public required bool ContainsEntity { get; init; }
    public required Entity? ContainedEntity { get; init; }

    public required bool GeneratesEntity { get; init; }
    public required Entity? GeneratedEntity { get; init; }
    public required int MaxGenerationCount { get; init; }

    public required bool ContainsWarp { get; init; }
    #endregion

    /// <summary>
    /// The amount of entities that have been generated by this tile already.
    /// </summary>
    public int GenerationCount { get; private set; } = 0;
}
